version: "3.8"

services:
  nextjs-app:
    build: .
    container_name: nextjs-app
    ports:
      - "3003:3000"  # Map host port 3003 to container port 3000
    networks:
      - default
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:latest
    container_name: wanderlust_prometheus
    ports:
      - "9090:9090"  # Exposing Prometheus UI on port 9090
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - default

  grafana:
    image: grafana/grafana:latest
    container_name: wanderlust_grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3001:3000"  # Exposing Grafana UI on port 3001
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - default
    depends_on:
      - prometheus

  jenkins:
    image: jenkins/jenkins:latest
    container_name: wanderlust_jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  grafana-data:
  jenkins_home:
