global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'jenkins'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['jenkins:8080']
  - job_name: 'nextjs-app'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['nextjs-app:3001']
